services:
  mock:
    image: brianjbayer/mock_random_thoughts_api:${MOCK_TAG:-latest}
    container_name: ${MOCK_HOSTNAME:-mock}
    environment:
      - PORT
    ports:
    - ${PORT:-3000}:${PORT:-3000}
    healthcheck:
      test: ["CMD", "bash", "-c", "node", "is_ok.js", "http://localhost:${PORT:-3000}/readyz"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 10
